### ISSUE TITLE
Emerging cross-linux-headers failed in musl-builder

### ISSUE THREAD

**Issue by soredake** [edannenberg/gentoo-bb#47] opened 2017-01-07 18:53 UTC
log https://transfer.sh/U5vHf/cross-x86-64-pc-linux-musl-linux-headers.log.xz
```
>>> Installing (2 of 6) sys-libs/pam-1.2.1-r99::musl
 * suid/sgid file(s) with suspicious hardlink(s):
 *
 *      /sbin/unix_chkpwd
 *
 * See the Gentoo Security Handbook guide for advice on how to proceed.

>>> Failed to install sys-libs/pam-1.2.1-r99, Log file:

>>>  '/var/tmp/portage/sys-libs/pam-1.2.1-r99/temp/build.log'
 * Messages for package sys-libs/pam-1.2.1-r99:
 * suid/sgid file(s) with suspicious hardlink(s):
 *
 *      /sbin/unix_chkpwd
 *
 * See the Gentoo Security Handbook guide for advice on how to proceed.
```

**Comment by edannenberg** [comment] 2017-01-09 09:17
Couldn't reproduce this with stage3 20170105. The error message suggests a file conflict on `/sbin/unix_chkpwd` due to reinstalling pam. Might be enough to remove that file, though I'm not sure how you got into this state in the first place. Got a branch/fork I can look at?

**Comment by soredake** [comment] 2017-01-09 14:29
after `./build.sh -sfFcC build fdsfgs` in says 
```
[ebuild  N    ~] cross-x86_64-pc-linux-musl/musl-1.1.16

The following keyword changes are necessary to proceed:
 (see "package.accept_keywords" in the portage(5) man page for more details)
# required by cross-x86_64-pc-linux-musl/musl (argument)
=cross-x86_64-pc-linux-musl/musl-1.1.16 ~amd64
```
some progress, yeah

**Comment by soredake** [comment] 2017-01-09 16:31
Aaaand stil produces the suid error with `./build.sh -sfFCc build fdsfgs`

**Comment by edannenberg** [comment] 2017-01-09 17:42
As I said, this looks like a filecheck gone wrong, i.e. the check looks in `/` and not in the custom `ROOT`. To work around that you could `mv` the file temporary. Can you post your Buildconfig.sh or is this with the vanilla `bob-musl` config? Did a rebuild from scratch today and `bob-musl` built without errors.

**Comment by soredake** [comment] 2017-01-09 17:47
>Buildconfig.sh
Vanilla.
>To work around that you could mv the file temporary.
I'm right now trying to build with `rm` before the crossdev.

**Comment by soredake** [comment] 2017-01-09 18:34
Success, but needed to stable the musl-1.1.16 and delete this file, even after the build from scratch it is required for me (strange).

**Comment by soredake** [comment] 2017-01-09 19:54
I'm so lucky, bob-musl for me requires the musl-1.1.16.

**Comment by edannenberg** [comment] 2017-01-10 14:51
Yep, last working musl ebuild (1.1.15) got removed upstream. As for the file check, I still couldn't reproduce this, did you maybe restart the old build container manually instead of starting a new build via `build.sh`?

**Comment by soredake** [comment] 2017-01-10 18:23
@edannenberg >did you maybe restart the old build container manually instead of starting a new build via build.sh?
I did not restarting the old build container.

I tried to build bob-musl again, after removing all the containers and the images that were previously. After i did `./build.sh -scF build gentoobb/glibc`

**Comment by edannenberg** [comment] 2017-01-12 06:21
Ok, just making sure. :) I noticed in your other musl issue from october that you had a similiar filecheck problem, which I also couldn't reproduce. So it seems to be related to rebuilds on error. I will close this for now in favour of the original musl issue, should the filecheck problem persist once musl is working again please open a new issue.

**Closed by edannenberg** 2017-01-12 06:21 UTC

**Comment by joluxer** [comment] 2019-06-26 09:04
I comment on this for those, who come across this by search engines, like me:
I was crossbuilding some Gentoo ARM Linux using docker with overlay graph driver. Despite the fact, that the resulting _visible_ filesystem has no duplicate references to the file `/sbin/unix_chkpwd`, there are several hard links counted by stat (in my case 43 hardlinks), where I assume now, that this is because of the docker overlay technology. 
So the multiple hardlink check while installing `sys-libs/pam` (in result of updating other packages like binutils, musl etc.) must fail with this error. 
The intermediate solution of deleting the offending file seems to me at the moment the only one, as the package `sys-libs/pam` is also in stage3 installs, so this and other files might show multiple hardlinks, depending on the container technology one is using.

**Comment by edannenberg** [comment] 2019-06-26 09:27
Yea this is a known issue with Docker `overlay1` storage driver. The best solution is using `overlay2` or some other storage driver. If that is not an option manually deleting the file(s) is probably your best [bet](https://github.com/edannenberg/kubler/blob/master/template/docker/builder/build_stage3.sh#L24).
